# Build stage to extract envsubst
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4 as envsubst

RUN microdnf -y install gettext

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4

ENV NGINX_VERSION 1.20.2-1.el9

LABEL name="nginxinc/nginx" \
    vendor="NGINX Inc." \
    version="${NGINX_VERSION}" \
    release="1" \
    summary="NGINX" \
    description="nginx will do ....."
## Required labels above - recommended below
LABEL url="https://www.nginx.com/" \
    io.k8s.display-name="NGINX" \
    io.openshift.expose-services="8080:http" \
    io.openshift.tags="nginx,nginxinc"

COPY nginx/nginx.repo /etc/yum.repos.d/nginx.repo

RUN curl -sO https://nginx.org/keys/nginx_signing.key && \
    rpm --import ./nginx_signing.key && \
    microdnf -y install --setopt=tsflags=nodocs nginx-${NGINX_VERSION}.ngx && \
    rm -f ./nginx_signing.key && \
    microdnf clean all

# forward request and error logs to docker log collector
# - Change pid file location & remove nginx user & change port to 8080
# - modify perms for non-root runtime
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log && \
    sed -i 's~/var/run/nginx.pid~/var/cache/nginx/nginx.pid~g' /etc/nginx/nginx.conf && \
    sed -i -e '/user/!b' -e '/nginx/!b' -e '/nginx/d' /etc/nginx/nginx.conf && \
    sed -i 's~/var/log/nginx/error.log warn~/var/log/nginx/error.log info~g' /etc/nginx/nginx.conf && \
    chown -R 998 /var/cache/nginx /etc/nginx && \
    rm -f /etc/nginx/conf.d/default.conf && \
    chmod -R g=u /var/cache/nginx /etc/nginx

EXPOSE 8080

RUN rm /usr/share/nginx/html/index.html

RUN chown 998 /usr/share/nginx/html

COPY nginx/nginx-gateway.conf.template nginx/nginx.sh /

COPY --from=envsubst /usr/bin/envsubst /usr/local/bin/

USER 998

CMD ["./nginx.sh"]
